// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mskvhzfrepqpsluzuelo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1za3ZoemZyZXBxcHNsdXp1ZWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODU0NjQsImV4cCI6MjA2MjY2MTQ2NH0.wxnVtxnGRbxKNgkqAzq6N-5T-68bj_p895KiCywngNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);